import '../../api/leagues/methods.js';
import '../../api/leagues/server/publications.js';
import '../../api/players/methods.js';
import '../../api/players/server/publications.js';
import '../../api/games/methods.js';
import '../../api/games/server/publications.js';
import '../../api/scores/methods.js';
import '../../api/scores/server/publications.js';
import '../../api/languages/methods.js';
